# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-03-01 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
